"""Initial migration with all drug fields

Revision ID: 2471abbc8a8e
Revises: 
Create Date: 2025-11-30 14:10:07.012289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2471abbc8a8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dosage_strength', sa.String(), nullable=True),
    sa.Column('package_size', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sa.String(), nullable=False),
    sa.Column('morning_pre_food', sa.Float(), nullable=False),
    sa.Column('morning_post_food', sa.Float(), nullable=False),
    sa.Column('evening_pre_food', sa.Float(), nullable=False),
    sa.Column('evening_post_food', sa.Float(), nullable=False),
    sa.Column('even_week_pills', sa.Float(), nullable=True),
    sa.Column('odd_week_pills', sa.Float(), nullable=True),
    sa.Column('current_amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('last_refilled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drugs_id'), 'drugs', ['id'], unique=False)
    op.create_index(op.f('ix_drugs_name'), 'drugs', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drugs_name'), table_name='drugs')
    op.drop_index(op.f('ix_drugs_id'), table_name='drugs')
    op.drop_table('drugs')
    # ### end Alembic commands ###
